notifications:
  email: false

language: node_js
cache:
  directories:
    - "node_modules"

node_js:
  - "node"
  - "lts/*"

script:
- npm install gauntface-theme
- npm run test

# after_script:
# - npm run report-coverage